/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustAndSafetyRouteImport } from './routes/trust-and-safety'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedOpportunitiesRouteImport } from './routes/saved-opportunities'
import { Route as QueryRelayRouteImport } from './routes/query-relay'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PostRouteImport } from './routes/post'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MyRelayRouteImport } from './routes/my-relay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EightStepJourneyRouteImport } from './routes/eight-step-journey'
import { Route as CorePillarsRouteImport } from './routes/core-pillars'
import { Route as BusinessProfileRouteImport } from './routes/business-profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R8StepJourneyRouteImport } from './routes/8-step-journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as RequestsSentRouteImport } from './routes/requests.sent'
import { Route as RequestsIncomingRouteImport } from './routes/requests.incoming'
import { Route as OpportunitiesMyRouteImport } from './routes/opportunities.my'
import { Route as InsightsAskRouteImport } from './routes/insights.ask'
import { Route as InsightsIdRouteImport } from './routes/insights.$id'
import { Route as ConnectionsIdRouteImport } from './routes/connections.$id'
import { Route as InsightsKnowledgeNewRouteImport } from './routes/insights.knowledge.new'
import { Route as InsightsKnowledgeIdRouteImport } from './routes/insights.knowledge.$id'
import { Route as InsightsKnowledgeIdEditRouteImport } from './routes/insights.knowledge.$id.edit'

const TrustAndSafetyRoute = TrustAndSafetyRouteImport.update({
  id: '/trust-and-safety',
  path: '/trust-and-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedOpportunitiesRoute = SavedOpportunitiesRouteImport.update({
  id: '/saved-opportunities',
  path: '/saved-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRelayRoute = QueryRelayRouteImport.update({
  id: '/query-relay',
  path: '/query-relay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRelayRoute = MyRelayRouteImport.update({
  id: '/my-relay',
  path: '/my-relay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EightStepJourneyRoute = EightStepJourneyRouteImport.update({
  id: '/eight-step-journey',
  path: '/eight-step-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CorePillarsRoute = CorePillarsRouteImport.update({
  id: '/core-pillars',
  path: '/core-pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R8StepJourneyRoute = R8StepJourneyRouteImport.update({
  id: '/8-step-journey',
  path: '/8-step-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const RequestsSentRoute = RequestsSentRouteImport.update({
  id: '/requests/sent',
  path: '/requests/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIncomingRoute = RequestsIncomingRouteImport.update({
  id: '/requests/incoming',
  path: '/requests/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesMyRoute = OpportunitiesMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const InsightsAskRoute = InsightsAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsIdRoute = InsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InsightsRoute,
} as any)
const ConnectionsIdRoute = ConnectionsIdRouteImport.update({
  id: '/connections/$id',
  path: '/connections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsKnowledgeNewRoute = InsightsKnowledgeNewRouteImport.update({
  id: '/knowledge/new',
  path: '/knowledge/new',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsKnowledgeIdRoute = InsightsKnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsKnowledgeIdEditRoute = InsightsKnowledgeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InsightsKnowledgeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/8-step-journey': typeof R8StepJourneyRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/business-profile': typeof BusinessProfileRoute
  '/core-pillars': typeof CorePillarsRoute
  '/eight-step-journey': typeof EightStepJourneyRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-relay': typeof MyRelayRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/post': typeof PostRoute
  '/proposals': typeof ProposalsRoute
  '/query-relay': typeof QueryRelayRoute
  '/saved-opportunities': typeof SavedOpportunitiesRoute
  '/signup': typeof SignupRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/connections/$id': typeof ConnectionsIdRoute
  '/insights/$id': typeof InsightsIdRoute
  '/insights/ask': typeof InsightsAskRoute
  '/opportunities/my': typeof OpportunitiesMyRoute
  '/requests/incoming': typeof RequestsIncomingRoute
  '/requests/sent': typeof RequestsSentRoute
  '/insights/': typeof InsightsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/insights/knowledge/$id': typeof InsightsKnowledgeIdRouteWithChildren
  '/insights/knowledge/new': typeof InsightsKnowledgeNewRoute
  '/insights/knowledge/$id/edit': typeof InsightsKnowledgeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/8-step-journey': typeof R8StepJourneyRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/business-profile': typeof BusinessProfileRoute
  '/core-pillars': typeof CorePillarsRoute
  '/eight-step-journey': typeof EightStepJourneyRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-relay': typeof MyRelayRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRoute
  '/proposals': typeof ProposalsRoute
  '/query-relay': typeof QueryRelayRoute
  '/saved-opportunities': typeof SavedOpportunitiesRoute
  '/signup': typeof SignupRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/connections/$id': typeof ConnectionsIdRoute
  '/insights/$id': typeof InsightsIdRoute
  '/insights/ask': typeof InsightsAskRoute
  '/opportunities/my': typeof OpportunitiesMyRoute
  '/requests/incoming': typeof RequestsIncomingRoute
  '/requests/sent': typeof RequestsSentRoute
  '/insights': typeof InsightsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/insights/knowledge/$id': typeof InsightsKnowledgeIdRouteWithChildren
  '/insights/knowledge/new': typeof InsightsKnowledgeNewRoute
  '/insights/knowledge/$id/edit': typeof InsightsKnowledgeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/8-step-journey': typeof R8StepJourneyRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/business-profile': typeof BusinessProfileRoute
  '/core-pillars': typeof CorePillarsRoute
  '/eight-step-journey': typeof EightStepJourneyRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-relay': typeof MyRelayRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/post': typeof PostRoute
  '/proposals': typeof ProposalsRoute
  '/query-relay': typeof QueryRelayRoute
  '/saved-opportunities': typeof SavedOpportunitiesRoute
  '/signup': typeof SignupRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/connections/$id': typeof ConnectionsIdRoute
  '/insights/$id': typeof InsightsIdRoute
  '/insights/ask': typeof InsightsAskRoute
  '/opportunities/my': typeof OpportunitiesMyRoute
  '/requests/incoming': typeof RequestsIncomingRoute
  '/requests/sent': typeof RequestsSentRoute
  '/insights/': typeof InsightsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/insights/knowledge/$id': typeof InsightsKnowledgeIdRouteWithChildren
  '/insights/knowledge/new': typeof InsightsKnowledgeNewRoute
  '/insights/knowledge/$id/edit': typeof InsightsKnowledgeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/8-step-journey'
    | '/about'
    | '/admin'
    | '/business-profile'
    | '/core-pillars'
    | '/eight-step-journey'
    | '/faq'
    | '/home'
    | '/insights'
    | '/login'
    | '/my-relay'
    | '/network'
    | '/onboarding'
    | '/opportunities'
    | '/post'
    | '/proposals'
    | '/query-relay'
    | '/saved-opportunities'
    | '/signup'
    | '/trust-and-safety'
    | '/connections/$id'
    | '/insights/$id'
    | '/insights/ask'
    | '/opportunities/my'
    | '/requests/incoming'
    | '/requests/sent'
    | '/insights/'
    | '/opportunities/'
    | '/insights/knowledge/$id'
    | '/insights/knowledge/new'
    | '/insights/knowledge/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/8-step-journey'
    | '/about'
    | '/admin'
    | '/business-profile'
    | '/core-pillars'
    | '/eight-step-journey'
    | '/faq'
    | '/home'
    | '/login'
    | '/my-relay'
    | '/network'
    | '/onboarding'
    | '/post'
    | '/proposals'
    | '/query-relay'
    | '/saved-opportunities'
    | '/signup'
    | '/trust-and-safety'
    | '/connections/$id'
    | '/insights/$id'
    | '/insights/ask'
    | '/opportunities/my'
    | '/requests/incoming'
    | '/requests/sent'
    | '/insights'
    | '/opportunities'
    | '/insights/knowledge/$id'
    | '/insights/knowledge/new'
    | '/insights/knowledge/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/8-step-journey'
    | '/about'
    | '/admin'
    | '/business-profile'
    | '/core-pillars'
    | '/eight-step-journey'
    | '/faq'
    | '/home'
    | '/insights'
    | '/login'
    | '/my-relay'
    | '/network'
    | '/onboarding'
    | '/opportunities'
    | '/post'
    | '/proposals'
    | '/query-relay'
    | '/saved-opportunities'
    | '/signup'
    | '/trust-and-safety'
    | '/connections/$id'
    | '/insights/$id'
    | '/insights/ask'
    | '/opportunities/my'
    | '/requests/incoming'
    | '/requests/sent'
    | '/insights/'
    | '/opportunities/'
    | '/insights/knowledge/$id'
    | '/insights/knowledge/new'
    | '/insights/knowledge/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R8StepJourneyRoute: typeof R8StepJourneyRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  CorePillarsRoute: typeof CorePillarsRoute
  EightStepJourneyRoute: typeof EightStepJourneyRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyRelayRoute: typeof MyRelayRoute
  NetworkRoute: typeof NetworkRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PostRoute: typeof PostRoute
  ProposalsRoute: typeof ProposalsRoute
  QueryRelayRoute: typeof QueryRelayRoute
  SavedOpportunitiesRoute: typeof SavedOpportunitiesRoute
  SignupRoute: typeof SignupRoute
  TrustAndSafetyRoute: typeof TrustAndSafetyRoute
  ConnectionsIdRoute: typeof ConnectionsIdRoute
  RequestsIncomingRoute: typeof RequestsIncomingRoute
  RequestsSentRoute: typeof RequestsSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-and-safety': {
      id: '/trust-and-safety'
      path: '/trust-and-safety'
      fullPath: '/trust-and-safety'
      preLoaderRoute: typeof TrustAndSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-opportunities': {
      id: '/saved-opportunities'
      path: '/saved-opportunities'
      fullPath: '/saved-opportunities'
      preLoaderRoute: typeof SavedOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-relay': {
      id: '/query-relay'
      path: '/query-relay'
      fullPath: '/query-relay'
      preLoaderRoute: typeof QueryRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-relay': {
      id: '/my-relay'
      path: '/my-relay'
      fullPath: '/my-relay'
      preLoaderRoute: typeof MyRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eight-step-journey': {
      id: '/eight-step-journey'
      path: '/eight-step-journey'
      fullPath: '/eight-step-journey'
      preLoaderRoute: typeof EightStepJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-pillars': {
      id: '/core-pillars'
      path: '/core-pillars'
      fullPath: '/core-pillars'
      preLoaderRoute: typeof CorePillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-profile': {
      id: '/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8-step-journey': {
      id: '/8-step-journey'
      path: '/8-step-journey'
      fullPath: '/8-step-journey'
      preLoaderRoute: typeof R8StepJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/requests/sent': {
      id: '/requests/sent'
      path: '/requests/sent'
      fullPath: '/requests/sent'
      preLoaderRoute: typeof RequestsSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/incoming': {
      id: '/requests/incoming'
      path: '/requests/incoming'
      fullPath: '/requests/incoming'
      preLoaderRoute: typeof RequestsIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/my': {
      id: '/opportunities/my'
      path: '/my'
      fullPath: '/opportunities/my'
      preLoaderRoute: typeof OpportunitiesMyRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/insights/ask': {
      id: '/insights/ask'
      path: '/ask'
      fullPath: '/insights/ask'
      preLoaderRoute: typeof InsightsAskRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$id': {
      id: '/insights/$id'
      path: '/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof InsightsIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/connections/$id': {
      id: '/connections/$id'
      path: '/connections/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof ConnectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/knowledge/new': {
      id: '/insights/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/insights/knowledge/new'
      preLoaderRoute: typeof InsightsKnowledgeNewRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/knowledge/$id': {
      id: '/insights/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/insights/knowledge/$id'
      preLoaderRoute: typeof InsightsKnowledgeIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/knowledge/$id/edit': {
      id: '/insights/knowledge/$id/edit'
      path: '/edit'
      fullPath: '/insights/knowledge/$id/edit'
      preLoaderRoute: typeof InsightsKnowledgeIdEditRouteImport
      parentRoute: typeof InsightsKnowledgeIdRoute
    }
  }
}

interface InsightsKnowledgeIdRouteChildren {
  InsightsKnowledgeIdEditRoute: typeof InsightsKnowledgeIdEditRoute
}

const InsightsKnowledgeIdRouteChildren: InsightsKnowledgeIdRouteChildren = {
  InsightsKnowledgeIdEditRoute: InsightsKnowledgeIdEditRoute,
}

const InsightsKnowledgeIdRouteWithChildren =
  InsightsKnowledgeIdRoute._addFileChildren(InsightsKnowledgeIdRouteChildren)

interface InsightsRouteChildren {
  InsightsIdRoute: typeof InsightsIdRoute
  InsightsAskRoute: typeof InsightsAskRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  InsightsKnowledgeIdRoute: typeof InsightsKnowledgeIdRouteWithChildren
  InsightsKnowledgeNewRoute: typeof InsightsKnowledgeNewRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsIdRoute: InsightsIdRoute,
  InsightsAskRoute: InsightsAskRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  InsightsKnowledgeIdRoute: InsightsKnowledgeIdRouteWithChildren,
  InsightsKnowledgeNewRoute: InsightsKnowledgeNewRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesMyRoute: typeof OpportunitiesMyRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesMyRoute: OpportunitiesMyRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R8StepJourneyRoute: R8StepJourneyRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  CorePillarsRoute: CorePillarsRoute,
  EightStepJourneyRoute: EightStepJourneyRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyRelayRoute: MyRelayRoute,
  NetworkRoute: NetworkRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PostRoute: PostRoute,
  ProposalsRoute: ProposalsRoute,
  QueryRelayRoute: QueryRelayRoute,
  SavedOpportunitiesRoute: SavedOpportunitiesRoute,
  SignupRoute: SignupRoute,
  TrustAndSafetyRoute: TrustAndSafetyRoute,
  ConnectionsIdRoute: ConnectionsIdRoute,
  RequestsIncomingRoute: RequestsIncomingRoute,
  RequestsSentRoute: RequestsSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
